### ISSUE TITLE
Universe Community Update, Issue 2

### ISSUE THREAD

**Issue by guylepage3** [universelabs/universe#10]
**Description**
Universe Community Update, Issue 2 - Bi-Weekly newsletter 
 
#9 Issue 1 - Mar 5, 2019

**Tasks**
- [x] Header imagery
  - [x] Highlight for imagery - Meta Docs
  - [x] Imagery
- [x] Overview
- [x] Current focus
- [x] Update
  - [x] Highlight for imagery - Universe.engineering
  - [x] Imagery

**Enhancements**
List possible improvements on the newsletter.
- [x] Add what's ahead section

**Comment by guylepage3** [comment]
**Newsletter**

Universe

![lepage-newsletter-issue-004-meta-docs@2x](https://user-images.githubusercontent.com/1711854/55415356-dd410200-553a-11e9-9442-7f32b06ce6a9.png)


## Universe Community Update, Issue 2
Tue, Apr 2, 2019

Welcome to the first .
Welcome to **Universe Community Update, Issue 2**.

The goal of this first newsletter is to update the community of the current focus and status of the project.

Let's make this newsletter better!

Please let me know if there's anything you'd like me to add or remove from the newsletter. [Contact Core Team](http://universe.engineering/contact). Feedback is welcome. Thank you.


### Current focus

We are moving back to an 80% focus on funding for Universe and 20% on product and growing the team.


### Update

The last few weeks have been filled with Meta product releases, key management scaffolding, funding and administrative work and inbound hiring.

We unintentionally, pulled back from funding and focused on product as well as managing quite a bit of inbound admin and HR.

On the key management side of things, we made some progress with architecture. And the open source community made some contributions to refactoring universe.engineering on the back end in anticipation for the v1 beta build.

With the public release of Meta v1.5 and documentation, we have been receiving great feedback from developers and have been making patch updates to both the software and documentation. If you have any issues or feature requests, please [let us know](https://github.com/universelabs/meta/issues).

There has been a spike in folks looking to work on the project. If you are wanting to work as a Core Team member at Universe Labs, the best thing you can do is [join the Slack](https://join.slack.com/t/universelabs/shared_invite/enQtNDQ0MjY3NDI5MTkwLTIzMWQ4M2U3MGQ3ZDY5MzM5MGQ5ZDM1MDZjNTgwNGI5NDdiNDY4ZDQyNWI2NjEzZmU3NzVmOTYwYzEzYzc1ZDE) and/or start [contributing to the project](https://github.com/universelabs/universe#contributing). All forms of contributions are welcome.

**Execution over the past few weeks**
- Refactoring of universe.engineering in prep for v1 beta key management software.
- Started on new architecture for universe.engineering.
- Released [Meta v1.5](https://github.com/universelabs/meta) with [Documentation](https://github.com/universelabs/meta/blob/master/DOCUMENTATION.md).
- Customer feedback and patch updates to Meta and Meta documentation.
- Research and development on the Universe Node hardware device.
- We've officially secured some pre-seed funds through a couple of investors (Announcement coming soon).
- Started working on a new Docs site for Meta, meta-ui.com.
- Started working on new open source product, UX Flow Sketch Library.
- Update to Meta UI Sketch Library.
- Started working on Cosmos, Blockstack, Universal Login, MetaMask integrations.


### What's Ahead?

In the coming weeks, we are looking to make some headway with universe.engineering key management software and finalize project funding. We will also be updating the Roadmap and announcing attendance at a couple of events.

**Comment by guylepage3** [comment]
Done. https://mailchi.mp/bbb5db9da597/universe-community-update-issue-2?e=fdddd686ac
