### ISSUE TITLE
Universe Community Update, Issue 3

### ISSUE THREAD

**Issue by guylepage3** [universelabs/universe#11]
**Description**
Universe Community Update, Issue 3 - Bi-Weekly newsletter.

**Reference(s)**
- #10 Issue 2 - Tue, Apr 2, 2019
-  Google Doc – https://docs.google.com/document/d/1AiCezZt0w06awmJ35yVq2FwrI2urr_LllL0TyFFn71w/edit#

**Tasks**

- [x] Overview.
- [x] Update.
- [x] What's next?
- [x] Header imagery. https://github.com/universelabs/universe-design/issues/38#issuecomment-518335182
- [x] Mobile device imagery. https://github.com/universelabs/universe-design/issues/38#issuecomment-518335127
- [x] Web app imagery. https://github.com/universelabs/universe-design/issues/38#issuecomment-518306003
- [x] UI update / build. https://github.com/universelabs/universe-design/issues/39

**Enhancements**
List possible improvements on the newsletter.

**Comment by guylepage3** [comment]
Pushing to Sprint 2.

**Comment by guylepage3** [comment]
Universe

[Header image ]
[Caption]

## Universe Community Update, Issue 3
Mon, Aug 5, 2019

Welcome to the 3rd Universe Community Update.

### Update

It's been a little while since our last community update. During that time we've made progress on all fronts.

**Pre-seed funding**

Our initial key focus was on pre-seed funding. Since our last update we worked on talking to investors and building relationships. We officially closed the pre-seed round in May.

**Focus: Team building**

After securing a very small round of pre-seed capital we then moved on to focusing on building the team. Universe has organically grown a small community of members who are passionate about our mission to assist the crypto community with mass adoption. We've also been receiving inbound potential hires ranging from all aspects, engineers, computer scientists, designers, marketers, sales people, etc. The result is that we now have a very strong and diverse team of dedicated, passionate and talented individuals from all backgrounds, platforms, careers, etc. who are wanting to join the team full time. See "Team" below for the full list.

Here's a quick list of folks we are very happy to introduce the new team

- **Guy Lepage**, _Co-founder, UX/UI Designer & Developer_ – (1st hire) Blockstack. Designer & developer on Blockstack Browser. 19+ yrs international award-winning designer. Managed brands such as Toyota, Whitecaps FC.
- **Itamar Reif**, _Co-founder, Software Engineer_ – Itamar is a 3rd year student at NYU currently working towards a Joint Major in Computer Science & Economics. Focus/interest in distributed systems and game theoretic algorithms.
- **Jacob Gadikian**, _Blockchain & Hardware Engineer_ – Tendermint/Cosmos blockchain developer. Formerly Co-founder of the Dawn Network, an early decentralized social network. Co-founder of bitcoin mine.
- **Dan Trevino**, _Blockchain Engineer & PM_ – Blockstack, Hyperledger Fabric, Tendermint/Cosmos developer. Founder of NoteRiot, early decentralized app. 15+ yrs working on projects for fortune 500's such as Nike, HP.
- **Modestos Kaffes**, _Front-End Engineer & Designer_ – Ethereum Dapp developer, Front-end software engineer with a strong design background and an eye for detail. 3+ yrs designer & engineer at Workable.
- **Charlotte Pan**, _UX & Product_ – UX & Product Designer with a passion for data visualization, front-end development, and designing products that make users’ lives easier.
- **Sean O’Connor**, _Marketing & Product_ – ConsenSys Product Marketer. Launched several consumer facing Dapps. Recently, Sean has been focused on improving Web3 UX and Advisor at Parsons School of Design.

**Advisors**

- **David Lee**, _Advisor_ – Former managing partner for SV Angel.
- **Adam Wood**, _Advisor_ – Twice named to FastCompany’s World’s Most Innovative Company (2016, 2019). Has shipped over $1B in new products including products for Amazon, Slack, Coinbase, etc.

**Product**

Funding and assembling the right team were critical initial steps over the past couple months. While testing out individuals for strengths and weaknesses, etc. We built and pushed the following in chronological order:

- **Web App (v1.0.1-alpha.1)** - Key management interface where users can sign up and use the copy/paste functionality to recover a Blockstack account.
- **Mobile Device (v0.1.0-alpha)** – A tiny Bluetooth device that caches a user's vault, acting as its decryption key to serve the web app.
- **Stationary Node (v0.1.1-alpha)** – A "home node" that will be used as cold storage, either locally or by interacting with a decentralized peer-to-peer storage swarm.

[Image ]
[Caption]


### What's Ahead?

With all the OKR’s complete, we are now starting to talk to investors about our seed fundraising round. And as we enter our seed round, we are few sprints out from having an alpha release of our mobile device ready for demoing. To get more info on the roadmap ahead, please visit the updated Roadmap either on universe.engineering or here on our GitHub repository.

Let's make this newsletter better!

Please let me know if there's anything you'd like me to add or remove from the newsletter. [Contact Core Team](http://universe.engineering/contact). Feedback is welcome. Thank you.

**Comment by guylepage3** [comment]
Moving this issue to [Sprint 6](https://github.com/orgs/universelabs/projects/7)

**Comment by faddat** [comment]
I think this is quite good.  

The main thing that I'd change is to move the invitation to make the update better to the bottom of the document.  I think that it would be a bit less jarring there.  Currently could take focus off of the update itself.

**Comment by guylepage3** [comment]
Great point @faddat. Will do.

**Comment by faddat** [comment]
Want a photo of the device for the update?

**Comment by guylepage3** [comment]
I am actually going to use the shell design from the deck for the visual of the mobile device. But thanks. 👍

**Comment by guylepage3** [comment]
Done
