### ISSUE TITLE
Roadmap: Stationary Node Hardware

### ISSUE THREAD

**Issue by faddat** [universelabs/universe#14]
**Our goal is 100% open hardware, with no compromises**
   
That said, if we want to ship quickly (and we do) then there will necessarily be compromises.  

Here's an article on what another company (System76) is doing to move progressively toward 100% open hardware on their line of computers:

https://opensource.com/article/19/4/system76-hardware

Basically, they're opening one sub-system at a time, and progressively moving towards a fully open platform.  Another open hardware company, [https://puri.sm](Purism) is taking roughly the same approach.  

When we say open, we mean open CPU, open GPU, open PCB, open software-- the whole stack.  Right now, we know that we can do open software, and we can maybe do open PCB (unless there are proprietary blobs there (interconnects), as well, and there very well may be) and we can certainly keep the hardware an "open platform" -- meaning that users will be able to run any software that they choose on it.  

**Tasks**
- [ ] Research relative platform openness and completeness-- ex: ARM (and ARM licensees vs one another-- they're not all the same with respect to openness) vs Intel vs AMD vs RISC-V; etc
- [ ] Determine the approximate spec for our first device.  
- [ ] Determine just how much of that device's hardware can be open by comparison between vendors
- [ ] Determine the openness-level of drivers for that platform
- [ ] See how binary-blobby (or not) a system image build will be for that platform

**Comment by guylepage3** [comment]
Great to have. Let's shelf this for the time being and revive it down the road. Great work here @faddat

**Comment by guylepage3** [comment]
Backlogging this issue for now.

**Comment by guylepage3** [comment]
Closing issue.
