### ISSUE TITLE
PM and update Sprint 6

### ISSUE THREAD

**Issue by guylepage3** [universelabs/universe#27]
**Description**
PM and update Sprint 6.

**Tasks**
- [x] Close and decipher tasks from Sprint 5 to Sprint 6.
- [x] Close Sprint 4.
- [x] Write out [Full Alpha Demo with Feather Device v0.3.0 Workflows](https://github.com/universelabs/universe-webapp/issues/46)
- [x] Add new Current Focus and Goal(s) for Sprint 6.
- [x] Build out [#28 Sprint 6 – Critical Path](https://github.com/universelabs/universe/issues/28)
- [x] Provide team with write up on Sprint 6.

**Comment by guylepage3** [comment]
Done
