### ISSUE TITLE
Sprint 6 – Critical Path

### ISSUE THREAD

**Issue by guylepage3** [universelabs/universe#28]
**Description**
The following is a critical path list of all tasks needed to execute to meet the goals for the release of the Full Alpha Demo with Feather Device.

For Sprint 6 we have the goal to get a full alpha demo with the feather working. The following tasks are required to do so.

**References**
- [#46 Customer journey for Alpha Demo w/ Feather device v0.3.0](https://github.com/universelabs/universe-webapp/issues/46)

**Tasks**
- [x] [universe-universe#34 ](https://github.com/universelabs/universe/issues/34) Universe architecture v1
- [x] [universe-webapp#51](https://github.com/universelabs/universe-webapp/issues/51) Bluetooth Javascript client
- [x] [universe-mobile#4](https://github.com/universelabs/universe-mobile/issues/4) BLE Server with CRUD capability
- [x] [universe-webapp#47](https://github.com/universelabs/universe-webapp/issues/47) Universe Feather alpha demo landing view build & UI
- [x] [universe-webapp#48](https://github.com/universelabs/universe-webapp/issues/48) Universe Feather alpha demo online instructions view build & UI
- [ ] [universe-webapp#49](https://github.com/universelabs/universe-webapp/issues/49) Universe Feather alpha demo connected view
- [ ] [universe-webapp#50](https://github.com/universelabs/universe-webapp/issues/50) Universe Feather alpha demo confirm password form (existing users)
- [x] ~~[universe-design#34](https://github.com/universelabs/universe-design/issues/34) Design packaging for Universe Feather device~~
- [x] ~~[universe-operations#57](https://github.com/universelabs/universe-operations/issues/57) Source and purchase printing for Universe Feather packaging~~
- [x] ~~[universe-design#35](https://github.com/universelabs/universe-design/issues/35) Print production for Universe Feather device packaging~~
- [x] [universe-design#36](https://github.com/universelabs/universe-design/issues/36) Design instruction card for Universe Feather packaging (PUSHED)
- [x] [universe-design#37](https://github.com/universelabs/universe-design/issues/37) Print production for Universe Feather instruction card (PUSHED)
- [ ] [universe-operations#56](https://github.com/universelabs/universe-operations/issues/56) Source and purchase Universe Feather devices
- [ ] [universe-core#3](https://github.com/universelabs/universe-core/issues/3) Week of 8/12 - Administrative Tasks
- [ ] [universe-core#2](https://github.com/universelabs/universe-core/issues/2) First steps
- [ ] [universe-core#4](https://github.com/universelabs/universe-core/issues/4) Basic Bluetooth Client
- [ ] [universe-core#5](https://github.com/universelabs/universe-core/issues/5) Blockstack Key Implementation
- [ ] [universe-core#6](https://github.com/universelabs/universe-core/issues/6) Login, Auth & Device Pairing

**If time**
- [ ] [universe-core#7](https://github.com/universelabs/universe-core/issues/7) Encryption facilities
