### ISSUE TITLE
Update roadmap

### ISSUE THREAD

**Issue by guylepage3** [universelabs/universe#41]
**Description**
Update roadmap.

**Comment by guylepage3** [comment]
# Universe Project Roadmap
_Last updated: Sep 9, 2019_

The following is the Universe Project Roadmap defining the project, technology, goals, and future milestones.

## Table of contents
- [Project Overview](#project-overview)
- [Goals](#goals)
- [Progress & Execution](#progress---execution)
- [Milestones](#milestones-unordered-list)
- [Current Tech Stack](#current-tech-stack)
- [Discovery](#discovery)
- [Use Cases](#use-cases)

## Project Overview
Universe Labs' mission is to become the world's largest decentralized login platform.

## Goals
- [ ] Decentralized Login (DLI) - Make login as secure as public key encryption and easier to use than passwords.
- [ ] Build out a strong and reliable core infrastructure and decentralized private key recovery protocol & network.
- [ ] Offer the best UX for private key management.
- [ ] Build and maintain software and a peer-to-peer protocol for handling transactions across the network.
- [ ] Build a large community of open source developers who contribute and integrate Universe's API & SDK.

## Progress to date

#### Team

We spent a couple months working on building a talented team of computer scientists, blockchain engineers, developers, designers and marketers.

- **Guy Lepage**, _**Co-founder**, UX/UI Designer & Developer_ ([Full Bio](https://lepage.cc/about)) – Guy was the 1st hire at [Blockstack PBC](https://blockstack.org), designer and 1 of 2 developers of the Blockstack browser. (assisted in the building of a company that raised over $53mm from USV, Naval Ravikant, Winklevoss', etc.).
- **Itamar Reif**, _**Co-founder**, Protocol Engineer_ – Itamar is a 3rd year student at NYU currently working towards a Joint Major in Computer Science & Economics. Focus/interest in distributed systems and algorithmic game theory.
- **Jacob Gadikian**, _**Co-founder**, _Blockchain & Hardware Engineer_ – Tendermint/Cosmos blockchain developer. Formerly Co-founder of the Dawn Network, an early decentralized social network. Co-founder of bitcoin mine.
- **Modestos Kaffes**, _Front-End Engineer & Designer_ – Ethereum DApp developer, Front-end software engineer with a strong design background and an eye for detail. 3+ yrs designer & engineer at Workable.
- **Charlotte Pan**, _UX & Product_ – UX & Product Designer with a passion for data visualization, front-end development, and designing products that make users’ lives easier.
- **Sean O’Connor**, _Marketing & Product_ – ConsenSys Product Marketer. Launched several consumer-facing DApps. Recently, Sean has been focused on improving Web3 UX and Advisor at Parsons School of Design.

#### Project Status
We've worked on defining a fully decentralized login and decentralized private key recovery protocol architecture. We are about to launch our decentralized login and move out of alpha into beta with our web app. In coming weeks users will be able to login with a simple click of a button on various Web 3.0 and Web 2.0 platforms and applications. Lastly, we have started building out our beta blockchain with utility token to bootstrap the network.

## Development Milestones (unordered list)

- [ ] Universe Key Management - Finish building out authentication on the key management web client.
- [ ] Universe Network - Cosmos-SDK blockchain for the Universe Network.
- [ ] Universe Growth - A code snippet that developers can use to integrate DLI. 
- [ ] Universe Growth - Hackathons to get developers building on Universe DLI.
- [ ] Universe Peer-to-Peer Storage - Design and develop a peer-to-peer storage system for decentralization of keys.

## Product Links
- Universe Key Management Web App – https://github.com/universelabs/universe-webapp
- GitHub – https://github.com/universelabs/universe
- GitHub (Universe Core) – https://github.com/universelabs/universe-core
- GitHub (Universe Web App) – https://github.com/universelabs/universe-webapp
- GitHub (Universe Key Manager) – https://github.com/universelabs/universe-key-manager
- Meta (Blockchain framework w/ 3,000+ downloads) – https://github.com/universelabs/meta
- Community – [Slack](https://join.slack.com/t/universelabs/shared_invite/enQtNDQ0MjY3NDI5MTkwLTIzMWQ4M2U3MGQ3ZDY5MzM5MGQ5ZDM1MDZjNTgwNGI5NDdiNDY4ZDQyNWI2NjEzZmU3NzVmOTYwYzEzYzc1ZDE)
- Website – https://universe.engineering

## Possible Future Technology
- Mobile hardware device for added user security
- Stationary hardware node for added key backup capabilities

## Partnerships
To be announced.

## Fundraising
To be announced.

## Current Tech Stack
- Bitcoin
- Ethereum
- Blockstack
- Cosmos-SDK
- C++
- Go
- Raspian Linux
- Raspberry Pi Hardware
- ESP32 Feather Hardware
- Node
- Express
- React
- Universe Meta (Universe's blockchain front-end framework)

**Comment by guylepage3** [comment]
@faddat @itamarreif @modkaffes @aseoconnor, please have a look when you get a moment. Thx.

**Comment by guylepage3** [comment]
Need to update to match website

**Comment by guylepage3** [comment]
Done
