### ISSUE TITLE
Move Sprint 7 issues to Sprint 8 board

### ISSUE THREAD

**Issue by guylepage3** [universelabs/universe#43]
**Description**
Move Sprint 7 issues to Sprint 8 board and add to critical path.

**Tasks**
- [x] Define this week's KPI (Key Performance Indicator).
- [x] Move sprint issues to new current sprint board.
- [x] Close previous sprint board and open upcoming sprint board.

**Comment by guylepage3** [comment]
Done
