### ISSUE TITLE
Move Sprint 8 issues to Sprint 9 board

### ISSUE THREAD

**Issue by guylepage3** [universelabs/universe#45]
**Description**
Move Sprint 8 issues to Sprint 9 board and add to critical path.

**Tasks**
- [x] Define this week's KPI (Key Performance Indicator).
- [x] Move sprint issues to new current sprint board.
- [x] Close previous sprint board and open upcoming sprint board.

**Comment by guylepage3** [comment]
Done.
