### ISSUE TITLE
Map Slack invite URL slack.universe.engineering to Slackin URL

### ISSUE THREAD

**Issue by guylepage3** [universelabs/universe#48]
**Description**
I’ve set us up with a new “Slack” invitation page with reCAPTCHA so that we can onboard users easier as well as not have to worry about the Slack invite links disappearing.

https://universelabs-slackin.herokuapp.com

As a result we now need to point https://universelabs-slackin.herokuapp.com to https://slack.universe.engineering.

**Tasks**
- [x] Map Slack invite URL to https://universelabs-slackin.herokuapp.com by creating a new CNAME record slack.universe.engineering.

**References**
- [CNAME Records (dnsimple.com)](https://support.dnsimple.com/articles/cname-record/)

**Comment by guylepage3** [comment]
Done..

![image](https://user-images.githubusercontent.com/1711854/65838682-ae320000-e2d3-11e9-9438-1cddc724c794.png)

**Comment by guylepage3** [comment]
Keeping this open until URL resolves.

**Comment by guylepage3** [comment]
Reopening issue as the mapping is broken.

**Comment by guylepage3** [comment]
From: DNSimple Support <support@dnsimple.com>
Date: Tue, Oct 1, 2019 at 8:30 PM
Subject: [DNSimple Support] Map URL to URL
To: <guylepage3@gmail.com>


Hi Guy Lepage,

We've received your support request and will get back to you with a response as quickly as possible, usually within 24 hours or less.

Here are some other things which might help in the mean time:
Visit http://support.dnsimple.com for frequently asked questions
If you're looking for the current DNSimple system status, visit http://dnsimplestatus.com/
We also publish updates on Twitter (http://twitter.com/dnsimple) and useful articles in our Blog (http://blog.dnsimple.com)

Sincerely,
The DNSimple Team

**Comment by guylepage3** [comment]
- [ ] Set the CNAME record that points the name slack.universe.engineering in [DNSimple.com](https://dnsimple.com/)
- [ ] Had to set the default team or organization `export HEROKU_ORGANIZATION=universe-labs`. See https://devcenter.heroku.com/articles/develop-orgs#setting-a-default-team.
- [ ] Then needed to set the subdomain to `slack.universe.engineering`. By running.. `heroku domains:add slack.universe.engineering --app=universelabs-slackin`.

**Comment by guylepage3** [comment]
Done

<img width="1920" alt="Screenshot 2019-10-02 08 50 54" src="https://user-images.githubusercontent.com/1711854/66045458-cc754700-e4f1-11e9-9956-9f665a3f6fbd.png">

**Comment by guylepage3** [comment]
https://slack.universe.engineering
