### ISSUE TITLE
Researching Cosmos

### ISSUE THREAD

**Issue by guylepage3** [universelabs/universe#50]
**Description**
As a result of deciding to go with Cosmos for our recovery app, @faddat will need to research some unknown unknowns.

**Tasks**
- [ ] Find out how fees work.
- [x] Find out how to acquire Atoms as we are in New York state and it's difficult to purchase them due to the bit license.

**Comment by faddat** [comment]
"Buying atoms"

**Comment by guylepage3** [comment]
@faddat i'll fill out the issue for you. :)

**Comment by guylepage3** [comment]
Add the the following issue description and tasks for @faddat 

**Description**
As a result of deciding to go with Cosmos for our recovery app, @faddat will need to research some unknown unknowns.

**Tasks**
- [ ] Find out how transactions work.
- [ ] Find out how to acquire Atoms as we are in New York state and it's difficult to purchase them due to the bit license.

**Comment by guylepage3** [comment]
@faddat were you able to purchase any Atoms?

**Comment by guylepage3** [comment]
From Slack for reference.

**Guy Lepage** 8:00 AM
@faddat good morning sir.. how did that purchase of $atoms go?

seems to be quite difficult to  purchase $atoms.

that’s a bit of an issue to discuss when talking about building on cosmos. can you put a pin on this?

**Comment by faddat** [comment]
# Atoms and NYS  / bitlicense

Impossible at this point. 

# Buying Atoms

Buying $atom went like this:

1) 

https://openmarketcap.com/cryptocurrency/atom-usd 

vs

https://coinmarketcap.com/currencies/cosmos/#markets

2) Due to OMC exchanges not operating in NYS, use hotbit from CMC, a KYC-free (ish) exchange (supposedly) based in mainland china.  

3) On Hotbit, exchange BTC for $atom at market rate

4) Once done on Hotbit, coins can (maybe) be stored on an Android cosmostation wallet or a ledger nano S.  Our coins aren't stored just yet.
