### ISSUE TITLE
Move Sprint 10 issues to Sprint 11 board

### ISSUE THREAD

**Issue by guylepage3** [universelabs/universe#51]
**Description**
Move Sprint 10 issues to Sprint 11 board and add to critical path.

**Tasks**
- [x] Set up new Sprint kanban board.
- [x] ~~Define this week's KPI (Key Performance Indicator).~~
- [x] Move sprint issues to new current sprint board.
- [x] Close previous sprint board.

**Comment by guylepage3** [comment]
Done
