### ISSUE TITLE
Sprint 11 – Critical Path

### ISSUE THREAD

**Issue by guylepage3** [universelabs/universe#52]
**Description**
The following is a critical path list of all tasks needed to execute to meet the goals for the release of the Universe Key Recovery App Alpha.

**Goals**
Get a full alpha where users can enter their back-up passphrase in order to "split" apart their back-up passphrase, and manually share 3 "parts" with 3 trustees. The user should also be able to combine the 3 "parts" in order to view the back-up passphrase. 
  - The app should utilize Shamir's Secret Sharing.

**References**
- [How to duplicate a git repository? (without forking)](https://stackoverflow.com/questions/6613166/how-to-duplicate-a-git-repository-without-forking/16762475)
- [#36 Engineering Call: Thu, Oct 10, 2019](https://github.com/universelabs/universe-team/issues/36)

**Other Critical Paths**
- [ ] ~~[#57 DigitalOcean migration – Critical Path](https://github.com/universelabs/universe/issues/57)~~ - Pushed to [Sprint 12](https://github.com/universelabs/universe/issues/59).
- [ ] ~~[#3 Key Recovery App (Free) v1.alpha – Critical Path](https://github.com/universelabs/universe-design-closed/issues/3)~~ - Pushed to [Sprint 12](https://github.com/universelabs/universe/issues/59).
- [ ] ~~[#2 Key Recovery App (Paid) v1.beta – Critical Path](https://github.com/universelabs/universe-design-closed/issues/2)~~ - Pushed to [Sprint 12](https://github.com/universelabs/universe/issues/59).

**Tasks**
- [x] @guylepage3 to pm sprint [#55 Sprint 11 project management](https://github.com/universelabs/universe/issues/55).
- [x] @faddat [#53 Create DigitalOcean Droplet for new Key Recovery Web App](https://github.com/universelabs/universe/issues/53).
- [x] @faddat [#1 Rename repository to `universe-key-recovery`](https://github.com/universelabs/universe-key-recovery/issues/1).
- [x] @faddat [#4 Duplicate universe.engineering for boilerplate](https://github.com/universelabs/universe-key-recovery/issues/4).
- [x] @faddat [#2 Remove Git history from the repository](https://github.com/universelabs/universe-key-recovery/issues/2).
- [x] @faddat @guylepage3 [#56 Understand how to run node.js apps on VM's](https://github.com/universelabs/universe/issues/56)
- [x] @faddat @guylepage3 [#79 Review & decide which service splitting method is fastest](https://github.com/universelabs/universe.engineering/issues/79).
- [x] @guylepage3 [#77 Pull out Mailchimp Express server for DigitalOcean migration](https://github.com/universelabs/universe.engineering/issues/77).
- [x] @guylepage3 [#81 Pull out Nodemailer Express server for DigitalOcean migration](https://github.com/universelabs/universe.engineering/issues/81)
- [ ] ~~@guylepage3 Design... [#3 Key Recovery Web App (Free) Design v1 – Critical Path](https://github.com/universelabs/universe-design-closed/issues/3)~~ - Pushed to [Sprint 12](https://github.com/universelabs/universe/issues/59).
  - [x] @guylepage3 [#1 Design v1 Key Recovery Web App (Free) dashboard](https://github.com/universelabs/universe-design-closed/issues/1).
  - [ ] ~~@guylepage3 Design v1 Key Recovery Web App (Free) Combine~~ - Pushed to [Sprint 12](https://github.com/universelabs/universe/issues/59).
  - [ ] ~~@guylepage3 Design v1 Key Recovery Web App (Free) Parts~~ - Pushed to [Sprint 12](https://github.com/universelabs/universe/issues/59).
- [x] @guylepage3 [#35 Seed Deck v3](https://github.com/universelabs/universe-team/issues/35).
- [x] @faddat [#1 Setup Nodemailer server virtual machine on DigitalOcean](https://github.com/universelabs/universe-nodemailer/issues/1).
- [x] @guylepage3 @faddat [#1 Setup email subscriptions server virtual machine on DigitalOcean](https://github.com/universelabs/universe-email-subscriptions/issues/1).
- [ ] ~~@guylepage3 [#71 Refactor & move client (universe.engineering) to DigitalOcean](https://github.com/universelabs/universe.engineering/issues/71)~~ - Pushed to [Sprint 12](https://github.com/universelabs/universe/issues/59).
- [ ] ~~@faddat [#3 Deploy web app to Digital Ocean](https://github.com/universelabs/universe-key-recovery/issues/3)~~ - Pushed to [Sprint 12](https://github.com/universelabs/universe/issues/59).
- [ ] ~~@guylepage3 Build out...~~ - Pushed to [Sprint 12](https://github.com/universelabs/universe/issues/59).
  - [ ] ~~Split view~~ - Pushed to [Sprint 12](https://github.com/universelabs/universe/issues/59).
  - [ ] ~~Share view~~ - Pushed to [Sprint 12](https://github.com/universelabs/universe/issues/59).
  - [ ] ~~Combine view~~ - Pushed to [Sprint 12](https://github.com/universelabs/universe/issues/59).
- [ ] ~~@guylepage3 build out part splitting~~ - Pushed to [Sprint 12](https://github.com/universelabs/universe/issues/59).
- [ ] ~~@guylepage3 build out part combining~~ - Pushed to [Sprint 12](https://github.com/universelabs/universe/issues/59).

**Comment by guylepage3** [comment]
Done
