### ISSUE TITLE
Sprint 11 project management

### ISSUE THREAD

**Issue by guylepage3** [universelabs/universe#55]
**Description**
PM'ing Sprint 11.

**Tasks**
- [x] Create [#52 Sprint 11 – Critical Path](https://github.com/universelabs/universe/issues/52).
- [x] Assign tasks to team.
  - [x] ~~Let teammates know to create their own issues.~~
- [x] Create issues for team.
- [x] Daily scrum calls.

Any other information you want to share that is relevant to the issue. This might include the lines of code, screenshots, imagery, links, solutions, opinions, feedback, etc.

**Comment by guylepage3** [comment]
Done
