### ISSUE TITLE
DigitalOcean migration – Critical Path

### ISSUE THREAD

**Issue by guylepage3** [universelabs/universe#57]
**Description**
We should be running each service on it's own instance so that we can utilize them across various products. Having said that, we need to pull out all back-end services out of web app, setup, run and test each service on their own instance (Digital Ocean), run the client (front-end) on it's own instance, then connect the back-end services to the front-end through API calls.

**Goals**
Pull out back-end services from current web app, have the back-end, the front-end running on their own instances and have them talking to each other on Digital Ocean.

```
NOTE: Execute in chronological order
```

**Tasks**
- [x] ~~@faddat [#79 Review & decide which service splitting method is fastest](https://github.com/universelabs/universe.engineering/issues/79) - _See **"Server split examples"** below for a great example on splitting up the back-end services_.~~ @guylepage3 @faddat decided to go with a individual services.
- [x] @guylepage3 [#77 Pull out Mailchimp Express server for DigitalOcean migration](https://github.com/universelabs/universe.engineering/issues/77)
- [x] @guylepage3 [#81 Pull out Nodemailer Express server for DigitalOcean migration](https://github.com/universelabs/universe.engineering/issues/81)
- [x] @faddat [#1 Setup Nodemailer server virtual machine on DigitalOcean](https://github.com/universelabs/universe-nodemailer/issues/1)
- [x] @guylepage3 [#1 Setup email subscriptions server virtual machine on DigitalOcean](https://github.com/universelabs/universe-subscriptions/issues/1)
- [ ] @guylepage3 [#71 Refactor & move client (universe.engineering) to DigitalOcean](https://github.com/universelabs/universe.engineering/issues/71)
- [ ] @faddat @guylepage3 Wire up API's to new universe.engineering client
- [ ] @guylepage3 [#67 Refactor & move web client (key management app) to DigitalOcean](https://github.com/universelabs/universe-webapp/issues/67)
- [ ] @faddat @guylepage3 Re-wire auth API to (key management app) client
- [ ] @faddat @guylepage3 Move name servers back to Google from DNSimple.
- [ ] @faddat @guylepage3 Setup DNS with DigitalOcean.

**NOTE**
@faddat Once all items in this issue are complete, write up findings and then close [#56 Understand how to run node.js apps on VM's](https://github.com/universelabs/universe/issues/56) issue. Thx.

**Server split examples**
- [Universe Key Management Web App - routes](https://github.com/universelabs/universe-webapp/blob/master/routes/index.js)
- [Universe Key Management Web App - routes - nodemailer (sendEmail)](https://github.com/universelabs/universe-webapp/blob/master/routes/sendEmail/index.js)
- [Universe Key Management Web App - routes - mailchimp (subscribe)](https://github.com/universelabs/universe-webapp/blob/master/routes/subscribe/index.js)

**References**
- [Express](https://expressjs.com/) - Web framework for Node.js.
- [Morgan](https://www.npmjs.com/package/morgan) - HTTP request logger middleware for node.js.
- [CORS](https://www.npmjs.com/package/cors) - CORS is a node.js package for providing a Connect/Express middleware that can be used to enable CORS with various options.
- [Body Parser](https://www.npmjs.com/package/body-parser) - Node.js body parsing middleware.
