### ISSUE TITLE
Sprint 12 – Critical Path

### ISSUE THREAD

**Issue by guylepage3** [universelabs/universe#59]
**Description**
The following is a critical path list of all tasks needed to execute to meet the goals for the release of the Universe Key Recovery App (Alpha).

**Goals**
Get a full alpha where users can enter a secret or backup phrase in order to "split" apart their backup phrase, and manually share 3 "parts" with 3 trustees. The user should also be able to combine the 3 "parts" in order to view the backup phrase. 
  - The app should utilize Shamir's Secret Sharing Scheme.

**Other Critical Paths**
- [ ] [#57 DigitalOcean migration – Critical Path](https://github.com/universelabs/universe/issues/57)
- [ ] [#3 Key Recovery App (Free) – Critical Path](https://github.com/universelabs/universe-design-closed/issues/3)
- [ ] [#2 Key Recovery App (Paid) – Critical Path](https://github.com/universelabs/universe-design-closed/issues/2)

**Tasks from Sprint 11**
- [ ] @guylepage3 Design... Key Recovery Web App (Free) Design v1.
  - [ ] @guylepage3 Design v1 Key Recovery Web App (Free) Combine.
  - [ ] @guylepage3 Design v1 Key Recovery Web App (Free) Parts.
- [ ] @guylepage3 [#71 Refactor & move client (universe.engineering) to DigitalOcean](https://github.com/universelabs/universe.engineering/issues/71).
- [ ] @faddat [#3 Deploy web app to Digital Ocean](https://github.com/universelabs/universe-key-recovery/issues/3).
- [ ] @guylepage3 Build out...
  - [ ] Split view.
  - [ ] Share view.
  - [ ] Combine view.
- [ ] @guylepage3 build out part splitting.
- [ ] @guylepage3 build out part combining.
- [ ] @guylepage3 Key Recovery Web App (Paid) Design v1.
