### ISSUE TITLE
Move Universe 14 issues to Universe 15 board

### ISSUE THREAD

**Issue by guylepage3** [universelabs/universe#64]
**Description**
Move issues to next board and add to critical path.

**Tasks**
- [x] ~~Create new "Move Universe [Current] issues to Universe [Next] board" issue and add it to the [Next] project~~.
  - [x] Closed [#3](https://github.com/universelabs/universe-design-private/issues/3) Key Recovery App (Free) v1.alpha – Critical Path.
  - [x] Closed [#57](https://github.com/universelabs/universe/issues/57) DigitalOcean migration – Critical Path.
- [x] Clean out "To do" column in preparation for moving issues to new sprint.
- [x] Move sprint issues to new current sprint board.
- [x] ~~Move issues to new current sprint critical path~~.
- [x] Update Project board "Navigation" note.
- [x] Update Project board "Finances" note.
- [x] Update Project board "Focus and Business KPI's" note.

**Reference(s)**
- Linking a repository to a project board - https://help.github.com/en/github/managing-your-work-on-github/linking-a-repository-to-a-project-board

**Comment by guylepage3** [comment]
Done
