### ISSUE TITLE
Set up Universe 16 board & critical path

### ISSUE THREAD

**Issue by guylepage3** [universelabs/universe#65]
**Description**
Set up sprint board and issues as well as setup critical path

**Tasks**
- [x] Create new project board by [copying previous project board](https://help.github.com/en/github/managing-your-work-on-github/copying-a-project-board).
- [x] Setup critical path.
- [x] Add "Navigation" note to kanban board.
- [x] Add "Finances" note to kanban board.
- [x] Add "Focus and Business KPI's" note to kanban board.

**Reference(s)**

**Comment by guylepage3** [comment]
Done
