### ISSUE TITLE
Move Universe 15 issues to Universe 16 board

### ISSUE THREAD

**Issue by guylepage3** [universelabs/universe#66]
**Description**
Move issues to next board and add to critical path.

**Tasks**
- [ ] Create new "Move Universe [Current] issues to Universe [Next] board" issue and add it to the [Next] project.
- [ ] Clean out "To do" column in preparation for moving issues to new sprint.
- [ ] Move sprint issues to new current sprint board.
- [ ] Move issues to new current sprint critical path.
- [ ] Update Project board "Navigation" note.
- [ ] Update Project board "Finances" note.
- [ ] Update Project board "Focus and Business KPI's" note.

**Reference(s)**
- Linking a repository to a project board - https://help.github.com/en/github/managing-your-work-on-github/linking-a-repository-to-a-project-board
