### ISSUE TITLE
Set up Universe 17 board & critical path

### ISSUE THREAD

**Issue by guylepage3** [universelabs/universe#67]
**Description**
Set up sprint board and issues as well as setup critical path

**Tasks**
- [ ] Create new project board by [copying previous project board](https://help.github.com/en/github/managing-your-work-on-github/copying-a-project-board).
- [ ] Setup critical path.
- [ ] Add "Navigation" note to kanban board.
- [ ] Add "Finances" note to kanban board.
- [ ] Add "Focus and Business KPI's" note to kanban board.

**Reference(s)**
